// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe224JQ2poe2doPFE8En7-RIEX2UfhyEg',
    appId: '1:119179858551:web:82eedb8cc5b5f08ddfac72',
    messagingSenderId: '119179858551',
    projectId: 'roqsalecommerce2026-6ce2c',
    authDomain: 'roqsalecommerce2026-6ce2c.firebaseapp.com',
    storageBucket: 'roqsalecommerce2026-6ce2c.firebasestorage.app',
    measurementId: 'G-0BBQFCP3ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIt4v0SxqV2FIKhRjy1Sla74axZP7lDw',
    appId: '1:119179858551:android:3a5da8e9735c9a73dfac72',
    messagingSenderId: '119179858551',
    projectId: 'roqsalecommerce2026-6ce2c',
    storageBucket: 'roqsalecommerce2026-6ce2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZcDEsjR-55GGzUU7_xLflG88GdKus5Zo',
    appId: '1:119179858551:ios:6f9447912afdac09dfac72',
    messagingSenderId: '119179858551',
    projectId: 'roqsalecommerce2026-6ce2c',
    storageBucket: 'roqsalecommerce2026-6ce2c.firebasestorage.app',
    iosBundleId: 'com.example.roqsalEcommerceDeliveryProject2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZcDEsjR-55GGzUU7_xLflG88GdKus5Zo',
    appId: '1:119179858551:ios:6f9447912afdac09dfac72',
    messagingSenderId: '119179858551',
    projectId: 'roqsalecommerce2026-6ce2c',
    storageBucket: 'roqsalecommerce2026-6ce2c.firebasestorage.app',
    iosBundleId: 'com.example.roqsalEcommerceDeliveryProject2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe224JQ2poe2doPFE8En7-RIEX2UfhyEg',
    appId: '1:119179858551:web:e70370b2f7ecea61dfac72',
    messagingSenderId: '119179858551',
    projectId: 'roqsalecommerce2026-6ce2c',
    authDomain: 'roqsalecommerce2026-6ce2c.firebaseapp.com',
    storageBucket: 'roqsalecommerce2026-6ce2c.firebasestorage.app',
    measurementId: 'G-V8BCN4RH3N',
  );
}
